# HOLLOW LABS — helper targets.

.PHONY: build release test lint fmt check demo sample run clean

build:
	cargo build

release:
	cargo build --release

test:
	cargo test --all

lint:
	cargo clippy --all-targets -- -D warnings

fmt:
	cargo fmt --all

# Everything CI runs.
check: fmt
	cargo fmt --all -- --check
	cargo clippy --all-targets -- -D warnings
	cargo test --all
	cargo build --release

# Demo gif: needs vhs (github.com/charmbracelet/vhs) and a release build.
demo: release
	vhs demo.tape

# Static demo transcript (always available, no vhs).
sample: release
	@mkdir -p docs
	@{ \
	  echo '# HOLLOW LABS — example run (`--dump`)'; \
	  echo; echo '> Generated by `make sample`. Fixed seed — reproducible.'; echo; \
	  for s in ddos bruteforce cred_spoof; do \
	    echo '```'; \
	    ./target/release/hollow-labs --dump $$s --seed 1337 --level advanced | head -n 40; \
	    echo '```'; echo; \
	  done; \
	} > docs/sample-run.md
	@echo "docs/sample-run.md updated"

run: release
	./target/release/hollow-labs

clean:
	cargo clean
	rm -f docs/demo.gif
